### ISSUE TITLE
An ActiveRecord::ConfigurationError occurred in exercises#index

### ISSUE THREAD

**Issue by jpslav** [openstax/exercises#88]
An ActiveRecord::ConfigurationError occurred in exercises#index:

  Association named 'publication' was not found on Publication; perhaps you misspelled it?
  lib/active_record/calculations_patch.rb:15:in `perform_calculation'

:error_id=>"430719"

This was on production

```
-------------------------------
Backtrace:
-------------------------------

  lib/active_record/calculations_patch.rb:15:in `perform_calculation'
  app/routines/search_exercises.rb:237:in `exec'
  app/controllers/api/v1/exercises_controller.rb:82:in `index'

-------------------------------
Data:
-------------------------------

  * data: {:error_id=>"430719",
   :class=>"ActiveRecord::ConfigurationError",
   :message=>
    "Association named 'publication' was not found on Publication; perhaps you misspelled it?",
   :first_line_of_backtrace=>
    "/home/ostexercises/src/exercises-cd23b1a/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/associations/join_dependency.rb:218:in `find_reflection'",
   :cause=>nil,
   :dns_name=>"unknown",
   :extras=>{}}
```

**Comment by Dantemss** [comment]
Well I can say production exercise search by content is broken :)

Priority: idk

**Comment by Dantemss** [comment]
Oh but apparently only broken when you are logged in as openstax...

**Comment by jpslav** [comment]
that's interesting!
